- name: "Linux Config"
  hosts:
    - all
  roles:
    - linux
  vars_files:
    - vars/prometheus__deploy.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

# - name: "Deploy Java"
#   hosts:
#     - all
#   roles:
#     - java
#   vars_files:
#     - vars/prometheus__deploy.yml
#   gather_facts: yes
#   become: yes
#   become_user: root
#   become_method: sudo

- name: "Deploy Prometheus Server"
  hosts:
    - prometheus_server
    - node_exporter
  roles:
    - prometheus
  vars_files:
    - vars/prometheus__deploy.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

- name: "Deploy Node Exporter"
  hosts:
    - node_exporter
  roles:
    - node_exporter
  vars_files:
    - vars/prometheus__deploy.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
