# %%%%%%%%%%%%%%%%%%%% ROLE: LINUX

# --- 开关

linux__enable_time: yes
linux__enable_time_ntp: yes

# --- 参数

# 操作系统时区
linux__timezone: "Asia/Shanghai"
linux__time_ntp_servers:
  - ntp.aliyun.com
  - ntp.tencent.com

linux__chrony_install_media: "chrony.zip"
linux__chrony_install_media_upload: "/upload/chrony"

linux__dir_yum_repofile_backup: "/upload/yum_repofile"

# %%%%%%%%%%%%%%%%%%%% ROLE: JAVA

java__install_media: "{{ dir__ansible_server__files }}/java/jdk-17.0.10_linux-x64_bin.tar.gz"
java__dir_base: "/usr/local"
java__dir_home: "{{ java__dir_base }}/jdk-17.0.10"

# %%%%%%%%%%%%%%%%%%%% ROLE: Grafana
grafana__server: "192.168.5.104"

# %%%%%%%%%%%%%%%%%%%% ROLE: Prometheus
prometheus__install_media: "{{ dir__ansible_server__files }}/prometheus/prometheus-3.0.1.linux-amd64.tar.gz"

prometheus__dir_upload: "/upload/prometheus"
prometheus__install_media_uploaded: "{{ prometheus__dir_upload }}/prometheus-3.0.1.linux-amd64"

prometheus__dir_base: "/opt"
prometheus__dir_home: "{{ prometheus__dir_base }}/prometheus"
prometheus__dir_scrape_config_files: "{{ prometheus__dir_home }}/scrape_config_files"

prometheus__dir_data: "/data/prometheus"

# %%%%%%%%%%%%%%%%%%%% ROLE: node_exporter
node_exporter__install_media: "{{ dir__ansible_server__files }}/node_exporter/node_exporter-1.8.2.linux-amd64.tar.gz"

node_exporter__dir_upload: "/upload/prometheus"
node_exporter__install_media_uploaded: "{{ node_exporter__dir_upload }}/node_exporter-1.8.2.linux-amd64"

node_exporter__dir_base: "/opt"
node_exporter__dir_home: "{{ node_exporter__dir_base }}/node_exporter"

node_exporter__file_log: "{{ node_exporter__dir_home }}/node_exporter.log"
