- name: "create directory"
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "{{ item }}"
  with_items:
    - "{{ prometheus__dir_upload }}"
    - "{{ prometheus__dir_home }}"

- name: "upload and uncompress Prometheus install media"
  unarchive:
    owner: root
    group: root
    mode: 0755
    src: "{{ prometheus__install_media }}"
    dest: "{{ prometheus__dir_upload }}"
